{{- if .Values.redis.enabled }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: redis-externalsecret
  namespace: {{ default "kuadrant-system" .Values.kuadrant.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: redis-config
    template:
      mergePolicy: Merge
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.redis.key }}
{{- end }}
