---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: {{ .Values.kuadrant.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: aws-credentials
    template:
      mergePolicy: Merge
      type: kuadrant.io/aws
  dataFrom:
  - extract:
      key: {{ .Values.awsCredentials.key }}
