apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kuadrant-operator-catalog
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/hook: "PreSync"
spec:
  sourceType: grpc
  image: quay.io/kuadrant/kuadrant-operator-catalog:v0.8.0
  displayName: Kuadrant Operators
  publisher: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
