apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Validate=false,PruneLast=true
{{- if .Values.redis.enabled }}
spec:
  limitador:
    storage:
      redis-cached:
        configSecretRef:
          name: {{ .Values.redis.secretName }}
{{- else }}
spec: {}
{{- end }}
