# Default values for kuadrant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Kuadrant Configuration
kuadrant:
  namespace: kuadrant-system

# External Secrets Configuration
# Vault secretStore definition
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

# Key and Path of secret provisioned in Vault
awsCredentials:
  key: secret/data/hub/awsCredentials

redis:
# Override to enable support for multicluster
  enabled: false
# External Secret Configuration
  secretName: redis-config
  key: secret/data/hub/redis
